name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm install -g npm@8

      - name: npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - run: npm run build
      - run: npm run typecheck
      - run: npm run test
      - run: npm run prettier:check

      - run: npm run docs:check # ts-node fatals on 12.x (?)
        if: ${{ matrix.node-version == '16.x' }}

      - run: git status --porcelain; test -z "$( git status --porcelain )"
